version: "3.4"

services:
  rabbit-mq:
    image: rabbitmq:3-management
    hostname: "rabbitmqrust"
    container_name: rust-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    networks:
      - rust-dev
  consumer:
    image: rust:1.62.1
    container_name: rust_rmq_consumer
    build:
      dockerfile: ./Dockerfile
      context: ./consumer/
    restart: on-failure
    depends_on:
      - rabbit-mq
    networks:
      - rust-dev

networks:
  rust-dev:
    driver: bridge
