[package]
name = "consumer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build]
target-dir = "./build"
[dependencies]
amiquip = "0.4.2"
dotenv = "0.15.0"
